;; Trusted streaming tar writer. Uploaded files are DATA, never Wasm modules.
;; Only WASI file operations are imported; no network or process execution.
(module
  (import "wasi_snapshot_preview1" "path_open"
    (func $open (param i32 i32 i32 i32 i32 i64 i64 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_read"
    (func $read (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_write"
    (func $write (param i32 i32 i32 i32) (result i32)))
  (import "wasi_snapshot_preview1" "fd_close" (func $close (param i32) (result i32)))
  (memory (export "memory") 2 2)
  (data (i32.const 64) "plan")
  (data (i32.const 80) "package.tar")
  ;; Addresses: iovec=0, transferred=8, opened fd=12, header=1024,
  ;; record fields=1536, source path=2048, zeros=8192, data buffer=16384.
  (func $check (param $errno i32)
    (if (local.get $errno) (then unreachable)))
  (func $openfile (param $dir i32) (param $path i32) (param $len i32)
                  (param $flags i32) (param $rights i64) (result i32)
    (call $check (call $open (local.get $dir) (i32.const 0)
      (local.get $path) (local.get $len) (local.get $flags)
      (local.get $rights) (i64.const 0) (i32.const 0) (i32.const 12)))
    (i32.load (i32.const 12)))
  (func $readexact (param $fd i32) (param $buf i32) (param $len i32)
    (local $n i32)
    (loop $again
      (i32.store (i32.const 0) (local.get $buf))
      (i32.store (i32.const 4) (local.get $len))
      (call $check (call $read (local.get $fd) (i32.const 0) (i32.const 1) (i32.const 8)))
      (local.set $n (i32.load (i32.const 8)))
      (if (i32.eqz (local.get $n)) (then unreachable))
      (local.set $buf (i32.add (local.get $buf) (local.get $n)))
      (local.set $len (i32.sub (local.get $len) (local.get $n)))
      (br_if $again (local.get $len))))
  (func $writeall (param $fd i32) (param $buf i32) (param $len i32)
    (local $n i32)
    (loop $again
      (i32.store (i32.const 0) (local.get $buf))
      (i32.store (i32.const 4) (local.get $len))
      (call $check (call $write (local.get $fd) (i32.const 0) (i32.const 1) (i32.const 8)))
      (local.set $n (i32.load (i32.const 8)))
      (if (i32.eqz (local.get $n)) (then unreachable))
      (local.set $buf (i32.add (local.get $buf) (local.get $n)))
      (local.set $len (i32.sub (local.get $len) (local.get $n)))
      (br_if $again (local.get $len))))
  (func (export "_start")
    (local $plan i32) (local $out i32) (local $source i32)
    (local $count i32) (local $pathlen i32) (local $size i32)
    (local $left i32) (local $chunk i32) (local $padding i32)
    (local.set $plan (call $openfile (i32.const 3) (i32.const 64) (i32.const 4)
      (i32.const 0) (i64.const 2)))
    (local.set $out (call $openfile (i32.const 4) (i32.const 80) (i32.const 11)
      (i32.const 9) (i64.const 64)))
    (call $readexact (local.get $plan) (i32.const 1536) (i32.const 4))
    (local.set $count (i32.load (i32.const 1536)))
    (if (i32.gt_u (local.get $count) (i32.const 10000)) (then unreachable))
    (block $done (loop $record
      (br_if $done (i32.eqz (local.get $count)))
      (call $readexact (local.get $plan) (i32.const 1024) (i32.const 512))
      (call $writeall (local.get $out) (i32.const 1024) (i32.const 512))
      (call $readexact (local.get $plan) (i32.const 1536) (i32.const 8))
      (local.set $pathlen (i32.load (i32.const 1536)))
      (local.set $size (i32.load (i32.const 1540)))
      (if (i32.gt_u (local.get $pathlen) (i32.const 4096)) (then unreachable))
      (if (i32.gt_u (local.get $size) (i32.const 1048576)) (then unreachable))
      (if (local.get $pathlen) (then
        (call $readexact (local.get $plan) (i32.const 2048) (local.get $pathlen))
        (local.set $source (call $openfile (i32.const 3) (i32.const 2048)
          (local.get $pathlen) (i32.const 0) (i64.const 2)))
        (local.set $left (local.get $size))
        (block $copied (loop $copy
          (br_if $copied (i32.eqz (local.get $left)))
          (local.set $chunk (local.get $left))
          (if (i32.gt_u (local.get $chunk) (i32.const 65536))
            (then (local.set $chunk (i32.const 65536))))
          (call $readexact (local.get $source) (i32.const 16384) (local.get $chunk))
          (call $writeall (local.get $out) (i32.const 16384) (local.get $chunk))
          (local.set $left (i32.sub (local.get $left) (local.get $chunk)))
          (br $copy)))
        (call $check (call $close (local.get $source)))))
      (local.set $padding (i32.and (i32.sub (i32.const 0) (local.get $size)) (i32.const 511)))
      (if (local.get $padding)
        (then (call $writeall (local.get $out) (i32.const 8192) (local.get $padding))))
      (local.set $count (i32.sub (local.get $count) (i32.const 1)))
      (br $record)))
    (call $writeall (local.get $out) (i32.const 8192) (i32.const 1024))
    (call $check (call $close (local.get $plan)))
    (call $check (call $close (local.get $out)))))
