apiVersion: v1
kind: ResourceQuota
metadata:
  name: flexy-workload-quota
spec:
  hard:
    pods: "40"
    count/jobs.batch: "20"
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 12Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: flexy-default-limits
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 1
        memory: 1Gi
