"""Strict, data-driven conversion recipes.

Recipes are an allowlist, not a best-effort Debian-to-Arch translator.  A package
must match every declared source field, payload path, digest, dependency constraint,
and target before a worker is permitted to construct a PKGBUILD.
"""

from __future__ import annotations

import json
import re
import shlex
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from .inspection import DebInspection


class RecipeError(ValueError):
    pass


@dataclass(frozen=True, slots=True)
class DependencyMapping:
    debian: str
    constraint: str
    arch: str


@dataclass(frozen=True, slots=True)
class Recipe:
    identifier: str
    package: str
    version: str
    architecture: str
    target_os: str
    target_architecture: str
    control_sha256: str | None
    files: dict[str, str]
    file_modes: dict[str, str]
    dependency_mappings: tuple[DependencyMapping, ...]
    pkgrel: int
    description: str
    license: str
    entrypoint: str
    launch_args: tuple[str, ...]
    functionality_args: tuple[str, ...]
    expected_launch_output: str | None
    expected_functionality_output: str | None

    @property
    def arch_dependencies(self) -> list[str]:
        return sorted({mapping.arch for mapping in self.dependency_mappings})

    def generated_pkgbuild(self) -> str:
        """Return only recipe-controlled shell source; uploaded metadata is never interpolated."""
        package_lines = []
        for path in sorted(self.files):
            mode = self.file_modes.get(path, "0644")
            # `path` is manifest-validated (no whitespace, traversal, or shell
            # metacharacter injection route), while the variables deliberately
            # remain double quoted so makepkg expands them at build time.
            # The staged, verified payload lives beside PKGBUILD.  `$srcdir` is a
            # makepkg-created scratch directory, whereas `$startdir` remains the
            # recipe's immutable work directory.
            source = f'"$startdir/payload/{path}"'
            destination = f'"$pkgdir/{path}"'
            package_lines.append("  install -Dm" + mode + " " + source + " " + destination)
        dependencies = " ".join(shlex.quote(item) for item in self.arch_dependencies)
        return "\n".join(
            [
                "# Generated by Flexy from an allowlisted recipe. Do not edit.",
                f"pkgname={shlex.quote(self.package)}",
                f"pkgver={shlex.quote(self.version)}",
                f"pkgrel={self.pkgrel}",
                f"pkgdesc={shlex.quote(self.description)}",
                f"arch=({shlex.quote(self.target_architecture)})",
                f"license=({shlex.quote(self.license)})",
                f"depends=({dependencies})",
                "options=(!strip)",
                "package() {",
                *package_lines,
                "}",
                "",
            ]
        )


@dataclass(frozen=True, slots=True)
class RecipeSelection:
    recipe: Recipe | None
    blockers: tuple[dict[str, Any], ...]
    mapped_dependencies: tuple[dict[str, str], ...]

    @property
    def supported(self) -> bool:
        return self.recipe is not None and not self.blockers


class RecipeRegistry:
    def __init__(self, recipes: list[Recipe]):
        identifiers = [recipe.identifier for recipe in recipes]
        if len(identifiers) != len(set(identifiers)):
            raise RecipeError("Duplicate recipe identifiers")
        self._recipes = {recipe.identifier: recipe for recipe in recipes}

    @classmethod
    def from_directory(cls, directory: Path) -> RecipeRegistry:
        recipes: list[Recipe] = []
        if not directory.exists():
            return cls([])
        for manifest_path in sorted(directory.glob("*.json")):
            try:
                data = json.loads(manifest_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError) as exc:
                raise RecipeError(f"Cannot load recipe manifest {manifest_path.name}") from exc
            recipes.append(_parse_recipe(data, manifest_path.name))
        return cls(recipes)

    def get(self, identifier: str | None) -> Recipe | None:
        return self._recipes.get(identifier or "")

    def select(
        self, inspection: DebInspection, target_os: str, target_architecture: str
    ) -> RecipeSelection:
        candidate_recipes = [
            recipe
            for recipe in self._recipes.values()
            if recipe.target_os == target_os and recipe.target_architecture == target_architecture
        ]
        shared_blockers = list(inspection.blockers)
        if not candidate_recipes:
            return RecipeSelection(
                recipe=None,
                blockers=tuple(
                    shared_blockers
                    + [
                        {
                            "code": "unsupported_target",
                            "message": (
                                f"No conversion recipes target {target_os}/{target_architecture}."
                            ),
                            "severity": "blocking",
                        }
                    ]
                ),
                mapped_dependencies=(),
            )

        near_misses: list[dict[str, Any]] = []
        for recipe in candidate_recipes:
            blockers, mappings = _recipe_match_blockers(recipe, inspection)
            if not blockers and not shared_blockers:
                return RecipeSelection(
                    recipe=recipe, blockers=(), mapped_dependencies=tuple(mappings)
                )
            near_misses.extend(blockers)
        # Deduplicate predictable mismatches, while retaining a useful reason rather
        # than exposing recipe implementation details to an anonymous caller.
        unique: list[dict[str, Any]] = []
        seen: set[tuple[str, str]] = set()
        for blocker in [*shared_blockers, *near_misses]:
            key = (str(blocker.get("code")), str(blocker.get("message")))
            if key not in seen:
                unique.append(blocker)
                seen.add(key)
        if not unique:
            unique.append(
                {
                    "code": "no_supported_recipe",
                    "message": "No exact supported conversion recipe matches this package.",
                    "severity": "blocking",
                }
            )
        return RecipeSelection(recipe=None, blockers=tuple(unique), mapped_dependencies=())


def _parse_recipe(data: dict[str, Any], source_name: str) -> Recipe:
    try:
        source = data["source"]
        target = data["target"]
        verification = data["verification"]
        files = source["files"]
        mappings = tuple(
            DependencyMapping(
                debian=str(item["debian"]),
                constraint=str(item.get("constraint", "")),
                arch=str(item["arch"]),
            )
            for item in data.get("dependencyMappings", [])
        )
        recipe = Recipe(
            identifier=str(data["id"]),
            package=str(source["package"]),
            version=str(source["version"]),
            architecture=str(source["architecture"]),
            target_os=str(target["os"]),
            target_architecture=str(target["architecture"]),
            control_sha256=str(source["controlSha256"]) if source.get("controlSha256") else None,
            files={
                _safe_recipe_path(path): _valid_sha256(digest) for path, digest in files.items()
            },
            file_modes={
                _safe_recipe_path(path): _valid_mode(mode)
                for path, mode in source.get("fileModes", {}).items()
            },
            dependency_mappings=mappings,
            pkgrel=int(data.get("pkgrel", 1)),
            description=str(data["description"]),
            license=str(data.get("license", "custom")),
            entrypoint=_safe_recipe_path(str(verification["entrypoint"])),
            launch_args=tuple(
                _safe_argument(item) for item in verification.get("launchArgs", ["--version"])
            ),
            functionality_args=tuple(
                _safe_argument(item)
                for item in verification.get("functionalityArgs", ["--self-test"])
            ),
            expected_launch_output=(
                str(verification["expectedLaunchOutput"])
                if verification.get("expectedLaunchOutput")
                else None
            ),
            expected_functionality_output=(
                str(verification["expectedFunctionalityOutput"])
                if verification.get("expectedFunctionalityOutput")
                else None
            ),
        )
    except (KeyError, TypeError, ValueError) as exc:
        raise RecipeError(f"Invalid recipe manifest {source_name}") from exc
    if not re.fullmatch(r"[a-z0-9@._+:-]{3,160}", recipe.identifier):
        raise RecipeError(f"Invalid recipe id in {source_name}")
    if not re.fullmatch(r"[a-z0-9@._+-]+", recipe.package):
        raise RecipeError(f"Invalid package name in {source_name}")
    if recipe.pkgrel < 1 or recipe.pkgrel > 1000 or not recipe.files:
        raise RecipeError(f"Invalid package release or file list in {source_name}")
    if set(recipe.file_modes) - set(recipe.files):
        raise RecipeError(f"Recipe {source_name} gives a mode for an undeclared file")
    if recipe.entrypoint not in recipe.files:
        raise RecipeError(f"Recipe {source_name} entrypoint is not a declared payload file")
    return recipe


def _safe_recipe_path(value: str) -> str:
    normalized = value.strip()
    path = PurePosixPath(normalized)
    if (
        not normalized
        or path.is_absolute()
        or ".." in path.parts
        or "\\" in normalized
        or "//" in normalized
        or not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._+@=/-]*", normalized)
    ):
        raise RecipeError("Recipe contains unsafe path")
    return str(path)


def _valid_sha256(value: Any) -> str:
    digest = str(value).lower()
    if not re.fullmatch(r"[0-9a-f]{64}", digest):
        raise RecipeError("Recipe contains invalid SHA-256")
    return digest


def _valid_mode(value: Any) -> str:
    mode = str(value)
    if not re.fullmatch(r"0?[0-7]{3}", mode):
        raise RecipeError("Recipe contains invalid file mode")
    return mode[-4:].rjust(4, "0")


def _safe_argument(value: Any) -> str:
    argument = str(value)
    if not argument or "\0" in argument or len(argument) > 256:
        raise RecipeError("Recipe contains unsafe verification argument")
    return argument


def _recipe_match_blockers(
    recipe: Recipe, inspection: DebInspection
) -> tuple[list[dict[str, Any]], list[dict[str, str]]]:
    blockers: list[dict[str, Any]] = []
    package = inspection.package
    for field, expected in (
        ("name", recipe.package),
        ("version", recipe.version),
        ("architecture", recipe.architecture),
    ):
        if package.get(field) != expected:
            blockers.append(
                {
                    "code": "recipe_source_mismatch",
                    "message": "Package metadata does not match a supported recipe version.",
                    "severity": "blocking",
                }
            )
            break
    if recipe.control_sha256 and inspection.control_sha256 != recipe.control_sha256:
        blockers.append(
            {
                "code": "recipe_control_hash_mismatch",
                "message": "Package control metadata differs from the supported recipe.",
                "severity": "blocking",
            }
        )
    actual_files = inspection.data_file_hashes
    if actual_files != recipe.files:
        blockers.append(
            {
                "code": "recipe_payload_mismatch",
                "message": "Package payload does not exactly match the supported recipe.",
                "severity": "blocking",
            }
        )
    mappings: list[dict[str, str]] = []
    mapping_index = {(item.debian, item.constraint): item for item in recipe.dependency_mappings}
    for dependency in inspection.dependencies:
        alternatives = dependency["alternatives"]
        supported_alternatives = [
            mapping_index.get((alternative["name"], alternative["constraint"]))
            for alternative in alternatives
            if mapping_index.get((alternative["name"], alternative["constraint"])) is not None
        ]
        if len(supported_alternatives) != 1:
            blockers.append(
                {
                    "code": "unsupported_dependency",
                    "message": (
                        f"Dependency '{dependency['raw']}' "
                        "has no explicit supported Arch mapping."
                    ),
                    "severity": "blocking",
                    "dependency": dependency["raw"],
                }
            )
        else:
            mapping = supported_alternatives[0]
            assert mapping is not None
            mappings.append(
                {"debian": mapping.debian, "arch": mapping.arch, "constraint": mapping.constraint}
            )
    return blockers, mappings
